/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/characters/character.glb -o src/components/models/Character.jsx -r public
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Character(props) {
  const { nodes, materials } = useGLTF('/models/characters/character.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ducky.geometry} material={materials.tiny_treats_1} scale={100} castShadow />
    </group>
  )
}

// Create a component for the character with proper scaling
export function CharacterWithPhysics({ position = [0, 0, 0], rotation = [0, 0, 0], scale = 2 }) {
  return (
    <group position={position} rotation={rotation}>
      <Character scale={scale} />
    </group>
  )
}

useGLTF.preload('/models/characters/character.glb')
